---

- name: Set up git for current user
  community.general.git_config:
    scope: global
    state: present
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop: "{{ gitconfig_list }}"

...
